EduardoS_301048660/Models/ViewModels/ClubCreateEditViewModel.cs
using EduardoS_301048660.Models.Poco;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace EduardoS_301048660.Models.ViewModels
{
    public class ClubCreateEditViewModel
    {
        public int ClubID { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Required]
        public string Address { get; set; }
        public IEnumerable<Player> Players { get; set; }
    }
}

EduardoS_301048660/Controllers/ClubController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduardoS_301048660.Models.Poco;
using EduardoS_301048660.Models.Repositories;
using EduardoS_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EduardoS_301048660.Controllers
{
    [Authorize]
    public class ClubController : Controller
    {
        private IClubRepository _clubRepository { get; }

        public ClubController(IClubRepository clubRepository) { _clubRepository = clubRepository; }

        [AllowAnonymous]
        public IActionResult Index() => View(_clubRepository.Clubs);

        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var club = _clubRepository.Get(id.Value);

            if (club == null)
            {
                return NotFound();
            }
            return View(club);
        }

        public IActionResult Create()
        {
            if (User.Identity.Name != "Admin") return RedirectToAction("Index", "Home");
            var club = new ClubCreateEditViewModel() { ClubID = -1 };
            return View(club);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ClubCreateEditViewModel club)
        {
            if (User.Identity.Name != "Admin") return RedirectToAction("Index", "Home");
            if (ModelState.IsValid)
            {

                var obj = new Club() {
                    ClubID = club.ClubID,
                    Name = club.Name,
                    Description = club.Description,
                    Address = club.Address
                };

                _clubRepository.Add(obj);
                TempData["message"] = $"{obj.Name} has been saved";
                return RedirectToAction(nameof(Index));
            }
            return View(club);
        }

        public IActionResult Edit(int? id)
        {
            if (User.Identity.Name != "Admin") return RedirectToAction("Index", "Home");
            if (id == null)
            {
                return NotFound();
            }

            var club = _clubRepository.Get(id.Value);

            if (club == null)
            {
                return NotFound();
            }


            var obj = new ClubCreateEditViewModel()
            {
                ClubID = club.ClubID,
                Name = club.Name,
                Description = club.Description,
                Address = club.Address,
                Players = club.Players
            };

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, ClubCreateEditViewModel club)
        {
            if (User.Identity.Name != "Admin") return RedirectToAction("Index", "Home");
            if (id != club.ClubID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var obj = new Club()
                    {
                        ClubID = club.ClubID,
                        Name = club.Name,
                        Description = club.Description,
                        Address = club.Address
                    };

                    _clubRepository.Update(obj);
                    TempData["message"] = $"{obj.Name} has been saved";
                }
                catch (Exception ex)
                {
                    if (!ClubExists(club.ClubID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           
            return View(club);
        }

        public IActionResult Delete(int? id)
        {
            if (User.Identity.Name != "Admin") return RedirectToAction("Index", "Home");
            if (id == null)
            {
                return NotFound();
            }

            var club = _clubRepository.Get(id.Value);

            if (club == null)
            {
                return NotFound();
            }
         
            return View(club);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (User.Identity.Name != "Admin") return RedirectToAction("Index", "Home");
            var club = _clubRepository.Get(id);

            if (club == null)
            {
                return NotFound();
            }

            _clubRepository.Delete(id);
            TempData["message"] = $"{club.Name} was deleted";
            return RedirectToAction(nameof(Index));
        }

        private bool ClubExists(int id)
        {
            return _clubRepository.Clubs.Any(e => e.ClubID == id);
        }

    }
}

EduardoS_301048660/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduardoS_301048660.Models.Poco;
using EduardoS_301048660.Models.Repositories;
using EduardoS_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EduardoS_301048660.Controllers
{
    [Authorize]
    public class PlayerController : Controller
    {
        private IPlayerRepository _playerRepository { get; }

        private IClubRepository _clubRepository { get; }

        public PlayerController(IPlayerRepository playerRepository, IClubRepository clubRepository)
        {
            _playerRepository = playerRepository;
            _clubRepository = clubRepository;
        }

        public IActionResult Index(int id = 0)
        {
            if (id > 0)
            {
                ViewBag.ClubName = _clubRepository.Get(id).Name;
                return View(_playerRepository.Players.Where(p=>p.ClubID == id));
            }
            return View(_playerRepository.Players);
        }

        public IActionResult Details(int? id)
        {
            if (!(User.Identity.Name == "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var player = _playerRepository.Get(id.Value);

            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        public IActionResult Create()
        {
            var model = new PlayerCreateEditViewModel() {
                ClubList = new List<SelectListItem>(),
                PlayerID = -1
            };

            foreach (var item in _clubRepository.Clubs)
                model.ClubList.Add(new SelectListItem { Value = item.ClubID.ToString(), Text = item.Name, Selected = item.ClubID == model.ClubID });

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(PlayerCreateEditViewModel player)
        {
            if (ModelState.IsValid)
            {
                var obj = new Player()
                {
                    PlayerID = player.PlayerID,
                    Name = player.Name,
                    Age = player.Age,
                    Address = player.Address,
                    ClubID = player.ClubID
                };

                _playerRepository.Add(obj);
                TempData["message"] = $"{obj.Name} has been saved";
                return RedirectToAction(nameof(Index), new { id = player.ClubID });
            }

            player.ClubList = new List<SelectListItem>();

            foreach (var item in _clubRepository.Clubs)
                player.ClubList.Add(new SelectListItem { Value = item.ClubID.ToString(), Text = item.Name, Selected = (item.ClubID == player.ClubID) });

            return View(player);
        }

        public IActionResult Edit(int? id)
        {
            if (!(User.Identity.Name == "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var player = _playerRepository.Get(id.Value);

            if (player == null)
            {
                return NotFound();
            }

            var obj = new PlayerCreateEditViewModel()
            {
                PlayerID = player.PlayerID,
                Name = player.Name,
                Age = player.Age,
                Address = player.Address,
                ClubID = player.ClubID,
                ClubList = new List<SelectListItem>()
            };

            foreach (var item in _clubRepository.Clubs)
                obj.ClubList.Add(new SelectListItem { Value = item.ClubID.ToString(), Text = item.Name, Selected = item.ClubID == obj.ClubID });

            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, PlayerCreateEditViewModel player)
        {
            if (!(User.Identity.Name == "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id != player.PlayerID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var obj = new Player()
                    {
                        PlayerID = player.PlayerID,
                        Name = player.Name,
                        Age = player.Age,
                        Address = player.Address,
                        ClubID = player.ClubID
                    };

                    _playerRepository.Update(obj);
                    TempData["message"] = $"{obj.Name} has been saved";
                }
                catch (Exception ex)
                {
                    if (!PlayerExists(player.PlayerID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index), new { id = player.ClubID });
            }

            player.ClubList = new List<SelectListItem>();

            foreach (var item in _clubRepository.Clubs)
                player.ClubList.Add(new SelectListItem { Value = item.ClubID.ToString(), Text = item.Name, Selected = item.ClubID == player.ClubID });

            return View(player);
        }

        public IActionResult Delete(int? id)
        {
            if (!(User.Identity.Name == "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (id == null)
            {
                return NotFound();
            }

            var player = _playerRepository.Get(id.Value);

            if (player == null)
            {
                return NotFound();
            }

            return View(player);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            if (!(User.Identity.Name == "Admin"))
            {
                return RedirectToAction("Index", "Home");
            }
            var player = _playerRepository.Get(id);
            
            if (player == null)
            {
                return NotFound();
            }

            var clubId = player.ClubID;

            _playerRepository.Delete(id);
            TempData["message"] = $"{player.Name} was Deregistered";
            return RedirectToAction(nameof(Index), new { id = clubId });
        }

        private bool PlayerExists(int id)
        {
            return _playerRepository.Players.Any(e => e.PlayerID == id);
        }

        public IActionResult Players(int id)
        {
            return View();
        }

    }
}

EduardoS_301048660/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduardoS_301048660.Models.Repositories;
using EduardoS_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EduardoS_301048660.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        private IPlayerRepository _playerRepository { get; }

        private IClubRepository _clubRepository { get; }

        public SearchController(IPlayerRepository playerRepository, IClubRepository clubRepository)
        {
            _playerRepository = playerRepository;
            _clubRepository = clubRepository;
        }

        public IActionResult Index(string query = "", string screen = "")
        {
            var model = new SearchViewModel();
            if (!string.IsNullOrEmpty(query))
            {
                model.Clubs = _clubRepository.Clubs.Where(p => p.Name.Contains(query)).ToList();
                model.Players = _playerRepository.Players.Where(p => p.Name.Contains(query)).ToList();
            }
            if (!string.IsNullOrEmpty(query))
            {
                model.Screen = screen;
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(SearchViewModel model)
        {
            if (!string.IsNullOrEmpty(model.Query))
            {
                model.Clubs = _clubRepository.Clubs.Where(p => p.Name.Contains(model.Query)).ToList();
                model.Players = _playerRepository.Players.Where(p => p.Name.Contains(model.Query)).ToList();
            }
            if (!string.IsNullOrEmpty(model.Query))
            {
                model.Screen = model.Screen;
            }
            return View(model);
        }

    }
}

EduardoS_301048660/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduardoS_301048660.Models.Repositories;
using EduardoS_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EduardoS_301048660.Controllers
{
    [Authorize]
    public class StatisticController : Controller
    {
        public int PageSize = 8;

        private IStatisticRepository _statisticRepository { get; }

        private IClubRepository _clubRepository { get; }

        public StatisticController(IStatisticRepository statisticRepository, IClubRepository clubRepository)
        {
            _statisticRepository = statisticRepository;
            _clubRepository = clubRepository;
        }

        public IActionResult Index(int club = 0, int year = 0, string position = "", int page = 1)
        {
            var model = new StatisticViewModel() {
                Club = club,
                Position = 
                position,
                Year = year
            };

            var items = _statisticRepository
                  .Statistics
                  .Where(p => model.Club == 0 || p.Club == model.Club)
                  .Where(p => model.Year == 0 || p.Year == model.Year)
                  .Where(p => string.IsNullOrEmpty(model.Position) || p.Position == model.Position);

            model.PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = items.Count()
            };

            model.Statistics = items
                   .OrderBy(p => p.StatisticID)
                   .Skip((page - 1) * PageSize)
                   .Take(PageSize)
                   .ToList();

            if (model.Club > 0)
            {
                model.Name = _clubRepository.Get(model.Club).Name;
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(StatisticViewModel model)
        {
            var qry = _statisticRepository.Statistics;
            
            if (model.Club > 0)
            {
                qry = qry.Where(p => p.Club == model.Club);
                model.Name = _clubRepository.Get(model.Club).Name;
            }

            if (model.Year > 0)
            {
                qry = qry.Where(p => p.Year == model.Year);
            }

            if (!string.IsNullOrEmpty(model.Position))
            {
                qry = qry.Where(p => p.Position == model.Position);
            }

            model.Statistics = qry.ToList();
            return View(model);
        }

    }
}

EduardoS_301048660/Views/Shared/_ClubCreateEdit.cshtml
@model ClubCreateEditViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="ClubID" />
<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Description" class="control-label"></label>
    <input asp-for="Description" class="form-control" />
    <span asp-validation-for="Description" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Address" class="control-label"></label>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>
</div>

EduardoS_301048660/Views/Shared/_ClubDetailsDelete.cshtml
@model Club

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Description)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Address)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Address)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ModifiedDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ModifiedDate)
    </dd>
</dl>

EduardoS_301048660/Views/Shared/_ClubList.cshtml
@model IEnumerable<Club>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            @if (User.Identity.IsAuthenticated)
            {
                if (User.Identity.Name == "Admin")
                {

                    <th class="th-controls"></th>

                }

            }
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-controller="Club" asp-action="Details" asp-route-id="@item.ClubID" class="not-btn">
                    @Html.DisplayFor(modelItem => item.Name)
                </a>
            </td>
            <td>
                <a asp-controller="Club" asp-action="Details" asp-route-id="@item.ClubID" class="not-btn">
                    @Html.DisplayFor(modelItem => item.Description)
                </a>
            </td>
            <td>
                <a asp-controller="Club" asp-action="Details" asp-route-id="@item.ClubID" class="not-btn">
                    @Html.DisplayFor(modelItem => item.Address)
                </a>
            </td>
            <td>
                <a asp-controller="Club" asp-action="Details" asp-route-id="@item.ClubID" class="not-btn">
                    @Html.DisplayFor(modelItem => item.ModifiedDate)
                </a>
            </td>
            @if (User.Identity.IsAuthenticated)
            {

                if (User.Identity.Name == "Admin")
                {
                    <td>
                        <form asp-controller="Club" asp-action="Delete" method="post">
                            <a asp-controller="Club" asp-action="Edit" asp-route-id="@item.ClubID">Edit</a> |
                            <input type="hidden" name="id" value="@item.ClubID" />
                            <button type="submit" class="btn btn-danger btn-sm">
                                Delete
                            </button>
                        </form>
                    </td>

                }


            }

        </tr>
        }
    </tbody>
</table>

EduardoS_301048660/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] - Club Soccer App - By Eduardo Santana to Centennial College</title>
    <link href="@Url.Content("~/css/site.css")" rel="stylesheet" />
</head>
<body>

    <div class="container">
        <div class="header">
            <h1>Club Soccer App</h1>
        </div>
        <div class="left">
            <div class="vertical-menu">

                @RenderSection("SearchBar", required: false)

                <a asp-controller="Home" asp-action="Index" class="@(ViewData["CurrentPage"]=="Home" ? "selected": "")">Home</a>
                <a asp-controller="Club" asp-action="Index" class="@(ViewData["CurrentPage"]=="Club" ? "selected": "")">Clubs Page</a>
                @if (User.Identity.IsAuthenticated)
                {
                    if (User.Identity.Name == "Admin")
                    {
                        <a asp-controller="Club" asp-action="Create" class="@(ViewData["CurrentPage"]=="ClubCreate" ? "selected": "")">Add Club</a>
                    }
                    <a asp-controller="Player" asp-action="Create" class="@(ViewData["CurrentPage"]=="PlayerCreate" ? "selected": "")">Register Player</a>
                    <a asp-controller="Statistic" asp-action="Index" class="@(ViewData["CurrentPage"]=="Statistic" ? "selected": "")">Statistic</a>
                    <a asp-action="Logout" asp-controller="Account">Log Out</a>
                }
                else
                {
                    <a asp-action="Login" asp-controller="Account">Log In</a>
                }
            </div>
        </div>
        <div class="right">
            <div class="render-body">
                @if (TempData["message"] != null)
                {
                    <div class="alert alert-success mt-1">@TempData["message"]</div>
                }
                @if (User.Identity.IsAuthenticated && ViewData["CurrentPage"] != "Statistic")
                {
                    <form asp-controller="Search" class="search-form" asp-action="Index">
                        <input type="hidden" name="Screen" value="@ViewData["CurrentPage"]" />
                        <label class="search-label">Search</label>
                        <input class="form-control" type="text" name="Query">
                        <button class="search-btn">
                            <img class="search-img" src="~/images/bg/loupe.png" />
                        </button>
                    </form>
                    <div style="clear:both;"></div>
                }
                @RenderBody()
            </div>
        </div>
        <div class="footer">
            <p>&copy; 2019 - Club Soccer App - By Eduardo Santana to Centennial College </p>
            @if (User.Identity.IsAuthenticated)
            {
                <p>Welcome to Club Soccer @User.Identity.Name User</p>
            }
        </div>
    </div>
    
</body>
</html>

EduardoS_301048660/Views/Shared/_PlayerCreateEdit.cshtml
@model PlayerCreateEditViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="PlayerID" />
<div class="form-group">
    <label asp-for="ClubID" class="control-label"></label>
    <select asp-for="ClubID" asp-items="Model.ClubList" class="form-control"></select>
    <span asp-validation-for="ClubID" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Age" class="control-label"></label>
    <input asp-for="Age" class="form-control" />
    <span asp-validation-for="Age" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Address" class="control-label"></label>
    <input asp-for="Address" class="form-control" />
    <span asp-validation-for="Address" class="text-danger"></span>
</div>

EduardoS_301048660/Views/Shared/_PlayerDetailsDelete.cshtml
@model Player

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.Club)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Club.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Age)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Age)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.Address)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.Address)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.ModifiedDate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ModifiedDate)
    </dd>
</dl>

EduardoS_301048660/Views/Shared/_PlayerList.cshtml
@model IEnumerable<Player>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            @if (ViewData["CurrentPage"] == "Player")
            {
                <th>
                    @Html.DisplayNameFor(model => model.Club)
                </th>
            }
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
            @if (ViewData["CurrentPage"] == "Player" || ViewData["CurrentPageAction"] == "Edit")
            {
                if (User.Identity.IsAuthenticated)
                {
                    if (User.Identity.Name == "Admin")
                    {

                    <th class="th-controls2"></th>
                    }
                }
            }
            </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Address)
            </td>
            @if (ViewData["CurrentPage"] == "Player")
            {
                <th>
                    @Html.DisplayFor(modelItem => item.Club.Name)
                </th>
            }
            <td>
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>
            @if (ViewData["CurrentPage"] == "Player" || ViewData["CurrentPageAction"] == "Edit")
            {

                if (User.Identity.IsAuthenticated)
                {

                    if (User.Identity.Name == "Admin")
                    {
                    <td>

                        <form asp-controller="Player" asp-action="Delete" method="post">
                            <a asp-controller="Player" asp-action="Edit" asp-route-id="@item.PlayerID">Reassigning</a> |
                            <input type="hidden" name="id" value="@item.PlayerID" />
                            <button type="submit" class="btn btn-danger btn-sm">
                                Deregistering
                            </button>
                        </form>

                    </td>
                    }
                }
                
            }
        </tr>
        }
    </tbody>
</table>