EduardoS_301048660/Models/Poco/Statistic.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;

namespace EduardoS_301048660.Models.Poco
{
    public class Statistic
    {
        public int StatisticID { get; set; }
        public string Player { get; set; }
        public int Goals { get; set; }
        [DisplayName("FH")]
        public int FirstHalf { get; set; }
        [DisplayName("SH")]
        public int SecondHalf { get; set; }
        [DisplayName("FS")]
        public int FirstScorer { get; set; }
        [DisplayName("LS")]
        public int LastScorer { get; set; }
        [DisplayName("H")]
        public int Home { get; set; }
        [DisplayName("A")]
        public int Away { get; set; }
        public int Year { get; set; }
        public int Club { get; set; }
        public string Position { get; set; }
    }
}

EduardoS_301048660/Models/ViewModels/StatisticViewModel.cs
using EduardoS_301048660.Models.Poco;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduardoS_301048660.Models.ViewModels
{
    public class StatisticViewModel
    {
        public string Name { get; set; }
        public int Club { get; set; }
        public int Year { get; set; }
        public string Position { get; set; }
        public string DisplayText
        {
            get
            {
                var retVal = "";

                if (!string.IsNullOrEmpty(this.Name))
                {
                    retVal += "Club " + Name;
                }

                if (this.Year > 0)
                {
                    if (!string.IsNullOrEmpty(retVal))
                    {
                        retVal += " And ";
                    }
                    retVal += " Year " + this.Year.ToString();
                }

                if (!string.IsNullOrEmpty(this.Position))
                {
                    if (!string.IsNullOrEmpty(retVal))
                    {
                        retVal += " And ";
                    }

                    retVal += "Position " + Position;
                }

                if (!string.IsNullOrEmpty(retVal))
                {
                    retVal = "for " + retVal;
                }

                return retVal;
            }
        }
        public List<Statistic> Statistics { get; set; }
        public PagingInfo PagingInfo { get; set; }
    }
}

EduardoS_301048660/Components/NavigationMenuViewComponent.cs
using EduardoS_301048660.Models.Repositories;
using EduardoS_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduardoS_301048660.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStatisticRepository _statisticRepository;
        private IClubRepository _clubRepository;

        public NavigationMenuViewComponent(IStatisticRepository statisticRepository, IClubRepository clubRepository)
        {
            _statisticRepository = statisticRepository;
            _clubRepository = clubRepository;
        }

        public IViewComponentResult Invoke()
        {
            var model = new SearchBarViewModel
            {
                Clubs = _clubRepository.Clubs.ToList(),
                Positions = _statisticRepository.Statistics.Select(p=>p.Position).Distinct().OrderBy(p=>p).ToList(),
                Years = _statisticRepository.Statistics.Select(p=>p.Year).Distinct().OrderBy(p=>p).ToList(),
                SelectedClub = (!string.IsNullOrEmpty(HttpContext?.Request?.Query["club"]) ? int.Parse(HttpContext?.Request?.Query["club"]) : 0),
                SelectedYear = (!string.IsNullOrEmpty(HttpContext?.Request?.Query["year"]) ? int.Parse(HttpContext?.Request?.Query["year"]) : 0),
                SelectedPosition = (!string.IsNullOrEmpty(HttpContext?.Request?.Query["position"]) ? HttpContext?.Request?.Query["position"].ToString() : "")
            };

            return View(model);
        }
    }
}

EduardoS_301048660/Controllers/StatisticController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EduardoS_301048660.Models.Repositories;
using EduardoS_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace EduardoS_301048660.Controllers
{
    [Authorize]
    public class StatisticController : Controller
    {
        public int PageSize = 8;

        private IStatisticRepository _statisticRepository { get; }

        private IClubRepository _clubRepository { get; }

        public StatisticController(IStatisticRepository statisticRepository, IClubRepository clubRepository)
        {
            _statisticRepository = statisticRepository;
            _clubRepository = clubRepository;
        }

        public IActionResult Index(int club = 0, int year = 0, string position = "", int page = 1)
        {
            var model = new StatisticViewModel() {
                Club = club,
                Position = 
                position,
                Year = year
            };

            var items = _statisticRepository
                  .Statistics
                  .Where(p => model.Club == 0 || p.Club == model.Club)
                  .Where(p => model.Year == 0 || p.Year == model.Year)
                  .Where(p => string.IsNullOrEmpty(model.Position) || p.Position == model.Position);

            model.PagingInfo = new PagingInfo
            {
                CurrentPage = page,
                ItemsPerPage = PageSize,
                TotalItems = items.Count()
            };

            model.Statistics = items
                   .OrderBy(p => p.StatisticID)
                   .Skip((page - 1) * PageSize)
                   .Take(PageSize)
                   .ToList();

            if (model.Club > 0)
            {
                model.Name = _clubRepository.Get(model.Club).Name;
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult Index(StatisticViewModel model)
        {
            var qry = _statisticRepository.Statistics;
            
            if (model.Club > 0)
            {
                qry = qry.Where(p => p.Club == model.Club);
                model.Name = _clubRepository.Get(model.Club).Name;
            }

            if (model.Year > 0)
            {
                qry = qry.Where(p => p.Year == model.Year);
            }

            if (!string.IsNullOrEmpty(model.Position))
            {
                qry = qry.Where(p => p.Position == model.Position);
            }

            model.Statistics = qry.ToList();
            return View(model);
        }

    }
}

EduardoS_301048660/Views/Statistic/Index.cshtml
@model StatisticViewModel

@{
    ViewData["Title"] = "Statistic top goal scorers";
    ViewData["CurrentPage"] = "Statistic";
}

<div class="content-header">
    <h2>@ViewData["Title"] @Model.DisplayText</h2>
    <hr />
</div>

<style>
    .player-img {
        margin: 0 10px;
        border: 0;
    }

    .key {
        width: 100%;
        float: left;
        height: auto;
        width: auto;
        margin: 16px 0;
        padding: 0px;
    }

        .key p {
            display: inline-block;
            float: left;
            margin: 0 10px 0 0;
            padding: 0 5px;
            line-height: 25px;
            color: #c1c1c1;
        }

    .tr-img {
        width: 30px;
    }

    .botton-pagination {
        float: right;
        margin-top: 15px;
    }

        .botton-pagination a {
            margin-left: 4px;
        }

        .botton-pagination .btn-primary {
            background-color: #01398f !important;
            border: 1px solid #17457a;
            border-radius: .25rem;
            color: white !important;
        }

        .botton-pagination a {
            border: 1px solid #17457a !important;
        }

    .btn-leyend {
        color:white !important;
    }
</style>

<p>This shows statistic of top goal scorers</p>

<table class="table">
    <thead>
        <tr>
            <th class="tr-img">

            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().Player)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().Goals)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().FirstHalf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().SecondHalf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().FirstScorer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().LastScorer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().Home)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Statistics.FirstOrDefault().Away)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Statistics)
        {
            <tr>
                <td>
                    <img class="player-img" src="~/images/bg/player.png" />
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Player)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Goals)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.FirstHalf)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.SecondHalf)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.FirstScorer)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.LastScorer)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Home)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Away)
                </td>
            </tr>
        }
    </tbody>
</table>

<div page-model="@Model.PagingInfo"
     page-action="Index"
     page-classes-enabled="true"
     page-class="btn"
     page-class-normal="btn-secondary"
     page-class-selected="btn-primary"
     page-url-year="@Model.Year"
     page-url-club="@Model.Club"
     page-url-position="@Model.Position"
     class="btn-group pull-right m-1 botton-pagination">
</div>

<div class="key">
    <p><b>FH</b> = First half,</p>
    <p><b>SH</b> = Second half,</p>
    <p><b>FS</b> = First scorer</p>
    <p><b>LS</b> = Last scorer</p>
    <p><b>H</b> = Home,</p>
    <p><b>A</b> = Away.</p>
</div>

@section SearchBar {
    @await Component.InvokeAsync("NavigationMenu")
}